default: &default
  recaptcha_public_key: 6Le4VgMTAAAAAG8kuI-hjaqnwBwdCqB6T-G5-CNo
  recaptcha_private_key: 6Le4VgMTAAAAAL2BVqT3VCegcGWXHKsrzGOWwPf_

development:
  <<: *default
  mail_password: AVZCmkJutGeueyrpK8JH2x!
  diploma_email_contact_form_password: SoMad5TLGZHuqXRqma4M
  blockcypher_api_token: <%= ENV["BLOCKCYPHER_API_TOKEN"] %>

production:
  <<: *default
  mail_password: AVZCmkJutGeueyrpK8JH2x
  diploma_email_contact_form_password: SoMad5TLGZHuqXRqma4M
  blockcypher_api_token: <%= ENV["BLOCKCYPHER_API_TOKEN"] %>