# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  sendgrid_api_key: <%= ENV["SENDGRID_API_KEY"] %>
  mailchimp_api_key: <%= ENV["MAILCHIMP_API_KEY"] %>
  mailchimp_list_id: <%= ENV["MAILCHIMP_LIST_ID"] %>
  google_omniauth_key: <%= ENV["GOOGLE_OMNIAUTH_KEY"] %>
  google_omniauth_secret: <%= ENV["GOOGLE_OMNIAUTH_SECRET"] %>
  domain_name: example.com
  mail_password: <%= Figaro.env.mail_password %>
  diploma_email_contact_form_password: <%= Figaro.env.diploma_email_contact_form_password %>
  secret_key_base: af9671fe831964c2afae79e31947a9a5d76503bd3498356215e567c3a20c90a0a01692b60de3cd6dfa5ec1a8b7120603d7edb029ec9d0dae3a9005badf8d30b3
  access_key_id: <%= ENV["AWS_ACCESS_KEY_ID"] %>
  secret_access_key: <%= ENV["AWS_SECRET_ACCESS_KEY"] %>
  mpk: <%= ENV["MPK"] %>
  msk: <%= ENV["MSK"] %>
  mpk_esilv: <%= ENV["MPK_ESILV"] %>
  msk_esilv: <%= ENV["MSK_ESILV"] %>
  mpk_essec: <%= ENV["MPK_ESSEC"] %>
  msk_essec: <%= ENV["MSK_ESSEC"] %>
  admin_uid: <%= ENV["ADMIN_UID"] %>

test:
  secret_key_base: bfa10f2dc1d09528e433dfa189ded6427d5a67c4272974829614684d534cc0bcac0eb7efbd8f266f80f8b2c2e8f873a55d1c31e93d76769fddbb45a81990f08f

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  mail_password: <%= Figaro.env.mail_password %>
  diploma_email_contact_form_password: <%= Figaro.env.diploma_email_contact_form_password %>
  sendgrid_api_key: <%= ENV["SENDGRID_API_KEY"] %>
  google_omniauth_key: <%= ENV["GOOGLE_OMNIAUTH_KEY"] %>
  google_omniauth_secret: <%= ENV["GOOGLE_OMNIAUTH_SECRET"] %>
  domain_name: <%= ENV["DOMAIN_NAME"] %>
  secret_key_base: 1e6e4191800b78bd9b61d063267b3e449f42460472e5ce42cd5cc984b0f924b8f5a232d31ee6cb18c465d24f77c97d3042e0d941902b025431c8f9f23bb569fe
  access_key_id: <%= ENV["AWS_ACCESS_KEY_ID"] %>
  secret_access_key: <%= ENV["AWS_SECRET_ACCESS_KEY"] %>
  mpk: <%= ENV["MPK"] %>
  msk: <%= ENV["MSK"] %>
  mpk_esilv: <%= ENV["MPK_ESILV"] %>
  msk_esilv: <%= ENV["MSK_ESILV"] %>
  mpk_essec: <%= ENV["MPK_ESSEC"] %>
  msk_essec: <%= ENV["MSK_ESSEC"] %>
  admin_uid: <%= ENV["ADMIN_UID"] %>